image: tshio/node-pipelines:latest

pipelines:
  default:
    - step:
        caches:
          - node
        services:
          - docker
        script:
          - npm run docker-build
          - npm run lint
          - npm run units

  custom:
    create-staging:
      - step:
          name: create staging environment
          image: tshio/awscli-docker-compose-pipelines:latest
          script:
            - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ECR_URL
            - docker build -t $AWS_ECR_URL:$BITBUCKET_COMMIT -f ./docker/prod/Dockerfile .
            - docker push $AWS_ECR_URL:$BITBUCKET_COMMIT
            - cd deploy/elastic-beanstalk
            - eb init --region eu-west-1 --platform "Multi-container Docker running on 64bit Amazon Linux" $APP_NAME
            - sed -i s,API_IMAGE,$AWS_ECR_URL:$BITBUCKET_COMMIT, Dockerrun.aws.json
            - cat Dockerrun.aws.json
            - eb create boilerplate-staging --database --database.engine postgres --database.password $RDS_PASSWORD --database.username $RDS_USERNAME --envvars REDIS_URL=redis://redis:6379/1,APP_NAME=$APP_NAME --instance_type t2.micro --elb-type classic --min-instances 1 --max-instances 1
          services:
            - docker
    deploy-backend:
      - step: 
          name: build docker image
          image: tshio/awscli-docker-compose-pipelines:latest
          script: 
            - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ECR_URL
            - docker build -t $AWS_ECR_URL:$BITBUCKET_COMMIT -f ./docker/prod/Dockerfile .
            - docker push $AWS_ECR_URL:$BITBUCKET_COMMIT
          services:
            - docker
      - step: 
          name: deploy api
          image: tshio/awscli-docker-compose-pipelines:latest
          script:
            - cd deploy/elastic-beanstalk
            - eb init --region eu-west-1 --platform "Multi-container Docker running on 64bit Amazon Linux" $APP_NAME
            - sed -i s,API_IMAGE,$AWS_ECR_URL:$BITBUCKET_COMMIT, Dockerrun.aws.json
            - eb deploy boilerplate-staging
          services:
            - docker  
