version: '3.4'

x-common: &common
  image: app-service:latest
  labels:
    com.app: app
  networks:
    - app
  volumes: &volumes
    - .:/app:delegated
    - build:/app/build/
    - ./node_modules:/app/node_modules/
    - node_dev:/usr/local/lib/node_modules/node-dev/

services:
  builder:
    <<: *common
    image: app:latest
    container_name: app-builder
    command: [sh, -c, './node_modules/.bin/tsc -w --pretty --skipLibCheck']

  base:
    labels:
      com.app: app
    networks:
      - app
    volumes:
      - .:/app:delegated
      - ./node_modules:/app/node_modules/
    image: app:latest
    container_name: app-base
    command: ['tail', '-f', '/dev/null']

  js:
    image: app:latest
    volumes: *volumes
    depends_on:
      - base
    networks:
      - app

  percent_api:
    <<: *common
    working_dir: /app/build
    container_name: percent_api
    command: [sh, -c, 'node-dev ./src/index.js --configKey percent_api']
    hostname: percent_api
    ports:
      - "1337:1337"

networks:
  app:

volumes:
  build:
  node_dev:
