version: '3.4'

x-common: &common
  image: app-service:latest
  labels:
    com.app: app
  env_file:
    - .env.dist
  # environment:
  #   REFRESH_TOKEN_EXPIRATION_TIME: $REFRESH_TOKEN_EXPIRATION_TIME
  #   REDIS_PERSIST_TIME: $REDIS_PERSIST_TIME
  #   ACCESS_TOKEN_EXPIRATION_TIME: $ACCESS_TOKEN_EXPIRATION_TIME
  #   EXTERNAL_AUTH_SECRET: $EXTERNAL_AUTH_SECRET
  #   ACCESS_TOKEN_KEY: $ACCESS_TOKEN_KEY
  #   REFRESH_TOKEN_KEY: $REFRESH_TOKEN_KEY
  networks:
    - app
  volumes:
    - build:/app/build/
    - node_dev:/usr/local/lib/node_modules/node-dev/

services:
  builder:
    <<: *common
    image: app:latest
    container_name: app-builder
    command: [sh, -c, 'rm -rf ./build/* && ./node_modules/.bin/tsc -w --pretty --skipLibCheck']

  js:
    image: app:latest
    depends_on:
      - postgres
    networks:
      - app

  percent_api:
    <<: *common
    working_dir: /app/build
    container_name: percent_api
    command: [sh, -c, 'node-dev ./src/index.js --configKey percent_api']
    hostname: percent_api
    depends_on:
      - postgres
    ports:
      - "1337:1337"

  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: percent
    networks:
      - app

networks:
  app:

volumes:
  build:
  node_dev:
